services:
  - type: web
    name: otp-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:5000 api_server:app
    envVars:
      PORT: 5000
